---
kind: Template
apiVersion: v1
metadata:
  name: grafana-ocp
  annotations:
    "openshift.io/display-name": Grafana ocp
    description: |
      Grafana server with patched Prometheus datasource.
    iconClass: icon-cogs
    tags: "metrics,monitoring,grafana,prometheus"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: grafana-ocp
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: grafana-ocp
  spec:
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: grafana-ocp:binaries
    source:
      dockerfile: |
        FROM centos:7

        MAINTAINER Eldad Marciano "mrsiano@gmail.com"

        ENV GOPATH /root/go


        RUN curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -

        RUN yum install -y --nogpgcheck \
            initscripts \
            curl \
            tar \
            gcc \
            libc6-dev \
            git \
            go \
            nodejs \
            bzip2 \
            bzip2-libs;

        RUN mkdir -p $GOPATH/src/github.com/grafana && \
            cd $GOPATH/src/github.com/grafana && pwd && \
            git clone https://github.com/mrsiano/grafana.git && \
            cd grafana && pwd && git branch -a && \
            git checkout OAuth;

        RUN cd $GOPATH/src/github.com/grafana/grafana && \
            go run build.go setup && \
            go run build.go build && \
            npm install -g yarn && \
            yarn install --pure-lockfile && \
            npm run build;

        WORKDIR /root/go/src/github.com/grafana/grafana
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: centos:7
        imageOptimizationPolicy: SkipLayers
    successfulBuildsHistoryLimit: 1
    triggers:
    - type: ConfigChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: grafana-ocp
    namespace: "${NAMESPACE}"
  spec:
    host: "${ROUTE_URL}"
    to:
      name: grafana-ocp
- apiVersion: v1
  kind: Service
  metadata:
    name: grafana-ocp
    namespace: "${NAMESPACE}"
    labels:
      metrics-infra: grafana-ocp
      name: grafana-ocp
  spec:
    selector:
      name: grafana-ocp
    ports:
    - port: 8082
      protocol: TCP
      targetPort: grafana-http
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: grafana-ocp
  spec:
    replicas: 1
    selector:
      deploymentconfig: grafana-ocp
    strategy:
      # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: grafana-ocp
      spec:
        volumes:
        - name: data
          emptyDir: {}
        containers:
        - image: "grafana-ocp:binaries"
          name: grafana-ocp
          ports:
          - name: grafana-http
            containerPort: 3000
          volumeMounts:
          - name: data
            mountPath: "/root/go/src/github.com/grafana/grafana/data"
          command:
          - "./bin/grafana-server"
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - grafana-ocp
        from:
          kind: ImageStreamTag
          name: grafana-ocp:binaries
      type: ImageChange
